name: Push-to-EC2

# Trigger deployment only on push to master branch
on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  
  deploy-to-modern:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: deploy to modern
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server 2
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST_PROD }}
          username: ${{ secrets.USERNAME_PROD }}
          key: ${{ secrets.KEY_PROD }}
          port: ${{ secrets.PORT_PROD }}
          script: |
            cd vintage
            git pull
            yarn
            yarn build
            pm2 update
  
  deploy:

    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd vintage
            git pull
            yarn
            yarn build
            pm2 update
