name: Deploy to Prod
on: workflow_dispatch

jobs:
  deploy-to-prod:
    name: deploy to prod
    runs-on: ubuntu-latest
    needs: [deploy]
    if: always() && (needs.deploy.result == 'success')
    steps:
      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST_PROD }}
          username: ${{ secrets.USERNAME_PROD }}
          key: ${{ secrets.KEY_PROD }}
          port: ${{ secrets.PORT_PROD }}
          script: |
            cd vintage
            git pull
            yarn
            yarn build
            pm2 update
