name: Push-to-EC2

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - main

jobs:
  deploy:

    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd vintage
            git pull
            yarn
            yarn build
            pm2 update
