name: Push-to-EC2

# Trigger deployment only on push to master branch
on: 
  push:
  workflow_dispatch:
    inputs:
        logLevel:
          description: 'Log level'     
          required: true
          default: 'warning' 
          type: choice
          options:
          - info
          - warning
          - debug 
        tags:
          description: 'Test scenario tags'
          required: false 
          type: boolean
        environment:
          description: 'Environment to run tests against'
          type: environment
          required: true 

jobs:

  deploy-to-modern:
    name: deploy to modern
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server 2
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST_PROD }}
          username: ${{ secrets.USERNAME }}
          key: ${{ env.KEY_PROD }}
          port: ${{ secrets.PORT }}
          script: |
            cd vintage
            git pull
            yarn
            yarn build
            pm2 update
  
  deploy:

    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd vintage
            git pull
            yarn
            yarn build
            pm2 update
